[package]
name = "farm-engine"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "farm_engine"
path = "src/lib.rs"

[dependencies]
ndarray.workspace = true
thiserror.workspace = true
